services:
  db:
    image: mysql:8.0
    container_name: musify_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: system
      MYSQL_DATABASE: musify_db
      MYSQL_USER: musify_user
      MYSQL_PASSWORD: musify_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_data: